server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/urban?useUnicode=true&autoReconnect=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: Root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        session_factory:
          statement_inspector: com.king.urban.core.jpa.JpaStatementInspector
    hibernate:
      ddl-auto: update
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: Redis@123
  liquibase:
    enabled: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
flowable:
  app:
    deploy-resources: false
  check-process-definitions: false
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: token
  # 是否输出操作日志
  is-log: true
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: off