server:
  port: 8888
spring:
  application:
    name: urban
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/urban?useUnicode=true&autoReconnect=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: Root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        session_factory:
          statement_inspector: com.king.urban.core.jpa.JpaStatementInspector
    hibernate:
      ddl-auto: update
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: Redis@123
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  liquibase:
    enabled: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
flowable:
  database-schema-update: false
  app:
    deploy-resources: false
  check-process-definitions: false